### ISSUE TITLE
Maybe move to Argo Labs

### ISSUE THREAD

**Issue by alexec** [jmckind/argocd-operator#38]
Would you like host this at https://github.com/argoproj-labs for kudo?

**Comment by jmckind** [comment]
Hey Alex! I would very much like to make the operator more official.

I have not really pushed it up to this point because I wanted to have something for people to get their hands on so to speak and use. I have been balancing the work on the operator with other priorities and as you can imagine, it's quite a lot of work to build a full featured operator from the ground up. That said, I am continuing to move forward with the operator and add the features with the goal of getting it to level 5 functionality listed on the operatorhub.io capability diagram.

https://operatorhub.io/static/images/capability-level-diagram.svg

**Comment by jmckind** [comment]
I would also like to submit the operator to operatorhub.io, but wanted the blessing of you all before I did that.

**Comment by alexec** [comment]
If I set it up would you be able to move it?

**Comment by jmckind** [comment]
Yes, no problem.

**Comment by alexec** [comment]
OK. Are you ready today - or do you want some time to tidy up things?

**Comment by alexec** [comment]
Here is the link: https://github.com/argoproj-labs/argocd-operator/invitations

**Comment by jmckind** [comment]
I will need to update some of the paths in the code. I will get on that first thing in the morning. Thanks!

**Comment by jmckind** [comment]
I have moved the repo over, all new development will be against this new repository.
https://github.com/argoproj-labs/argocd-operator

I will be working through any issue with the move and ensuring everything builds as expected. @alexec I am currently hosting the container image for the operator on my personal Quay account.
https://quay.io/repository/jmckind/argocd-operator

We can leave it here for now, but at some point I imagine that this should be moved as well.

FYI @disposab1e

**Comment by jmckind** [comment]
I will also be creating issues in the new repo that mirror the open issues here.

**Comment by alexec** [comment]
Sure! Let me know when it’s ready and we can let the community know

**Comment by jmckind** [comment]
Everything should be good, thanks again!

**Comment by jmckind** [comment]
Going to close this, all new issues for the argocd-operator should go here:

https://github.com/argoproj-labs/argocd-operator/issues
